### ISSUE TITLE
extractText broken

### ISSUE THREAD

**Issue by patroza** [easy-webpack/config-css#2] opened 2016-07-15 09:51 UTC
```
@easy-webpack\config-css\src\index.ts:31
        extractText = extractTextInstances.get(filename)
                                           ^
TypeError: extractTextInstances.get is not a function
```

The problem seems to be that the extractTextInstances in the metadata at some point gets JSON serialized and deserialized (perhaps by another part of the easy-webpack pipeline?), and thus it is no longer a Map, but an Object, and thus .get is not a function.

**Comment by niieani** [comment] 2016-07-15 09:55
This was recently fixed in `easy-webpack/assign`. Please run `npm update`.

**Closed as completed by niieani** 2016-07-15 09:55 UTC

**Comment by patroza** [comment] 2016-07-15 10:00
interesting, however npm update doesnt update easy-webpack/assign .. investigating..

Update: It started updating when running

```
npm i @easy-webpack/assign
npm -v
3.10.3
```

**Comment by niieani** [comment] 2016-07-15 10:02
`easy-webpack/assign` is a dependency of `easy-webpack/core`, try `npm install @easy-webpack/core --save-dev`.

**Comment by niieani** [comment] 2016-07-15 10:04
Fixed in https://github.com/easy-webpack/assign/commit/a6fb46a2986a87ec94151630f9e7d0c1154b8752 which is released as v0.9.12.

**Comment by patroza** [comment] 2016-07-15 10:08
Then getting

```
node_modules\webpack\lib\Compilation.js:457
                rebuilding.forEach(function(cb) {
             ^
TypeError: Cannot read property 'node_modules\@easy-webpack\config-css\node_modules\extract-text-webpack-plugin' of null
    at node_modules\@easy-webpack\config-css\node_modules\extract-text-webpack-plugin\index.js:230:27
    at node_modules\webpack\lib\Compilation.js:458:4
    at Array.forEach (native)
    at callback (node_modules\webpack\lib\Compilation.js:457:14)
    at Compilation.<anonymous> (node_modules\webpack\lib\Compilation.js:478:4)
    at node_modules\webpack\lib\Compilation.js:325:10
    at node_modules\webpack\node_modules\async\lib\async.js:52:16
    at Object.async.forEachOf.async.eachOf (node_modules\webpack\node_modules\async\lib\async.js:236:30)
    at Object.async.forEach.async.each (node_modules\webpack\node_modules\async\lib\async.js:209:22)
    at Compilation.addModuleDependencies (node_modules\webpack\lib\Compilation.js:194:8)
    at Compilation.processModuleDependencies (node_modules\webpack\lib\Compilation.js:179:7)
```

**Comment by niieani** [comment] 2016-07-15 10:11
Trying to reproduce on a freshly pulled skeleton-nav.

**Comment by niieani** [comment] 2016-07-15 10:20
I'm unable to reproduce on a fresh skeleton. Try removing `node_modules` and run `npm install`; should fix.
